# Análise de Dados de Filmes Exibidos no Brasil de 2009 a 2019
Com base nos dados da ANCINE (https://oca.ancine.gov.br/cinema)

In [2]:
import pandas as pd
%matplotlib inline

In [3]:
# Criar o DataFrame com base no arquivo Exel
# Pular as 2 primeiras linhas (skiprows)
df = pd.read_excel('2122.xlsx', skiprows = 2, skipfooter = 19)

In [4]:
df.head()

,Ano de exibição,Semana de exibição,CPB/ROE,Título da obra,Gênero,País(es) produtor(es) da obra,Nacionalidade da obra,Data de Lançamento,Distribuidora,Origem da empresa distribuidora,Número de salas na semana dos dados,Público na semana dos dados,Renda (R$) na semana dos dados
0,2009,semana 01,E1402431200000,007 Quantum of Solace,Ficção,"Estados Unidos, Inglaterra",Estrangeira,2008-11-07 00:00:00,Sony,Distribuição Internacional,31,4597,24719.0
1,2009,semana 01,B0700678800000,5 Frações de uma Quase História,Ficção,Brasil,Brasileira,2008-05-09 00:00:00,Usina Digital,Distribuição Nacional,1,24,120.5
2,2009,semana 01,E1600541500000,A Alegria de Emma,Ficção,Alemanha,Estrangeira,2008-10-03 00:00:00,Pandora Filmes,Distribuição Nacional,1,42,700.0
3,2009,semana 01,E1600594000000,A Bela Junie,Ficção,França,Estrangeira,2009-01-01 00:00:00,Imovision,Distribuição Nacional,2,1331,15710.5
4,2009,semana 01,E1600127600000,A Casa das Coelhinhas,Ficção,Estados Unidos,Estrangeira,2008-10-10 00:00:00,Sony,Distribuição Internacional,4,402,2011.0

In [5]:
df.tail(21)

,Ano de exibição,Semana de exibição,CPB/ROE,Título da obra,Gênero,País(es) produtor(es) da obra,Nacionalidade da obra,Data de Lançamento,Distribuidora,Origem da empresa distribuidora,Número de salas na semana dos dados,Público na semana dos dados,Renda (R$) na semana dos dados
61113,2019,semana 52,E1900581900000,O Paraíso Deve Ser Aqui,Ficção,"Alemanha, Canadá, França, Qatar, Turquia",Estrangeira,2019-12-19 00:00:00,Imovision,Distribuição Nacional,19,7308,144108.0
61114,2019,semana 52,E1900267700000,O Rei Leão,Ficção,Estados Unidos,Estrangeira,2019-07-18 00:00:00,Disney,Distribuição Internacional,3,133,1437.0
61115,2019,semana 52,E1900483800000,O Reino Gelado: A Terra Dos Espelhos,Animação,Rússia,Estrangeira,2019-11-22 00:00:00,Galeria Distribuidora,Distribuição Nacional,26,2365,27973.0
61116,2019,semana 52,E1900304200000,O Relatório,Ficção,Estados Unidos,Estrangeira,2019-11-07 00:00:00,Diamond Films,Distribuição Nacional,1,10,133.0
61117,2019,semana 52,E1900268100000,O Último Amor De Casanova,Ficção,França,Estrangeira,2019-12-26 00:00:00,Califórnia,Distribuição Nacional,28,2860,49321.0
61118,2019,semana 52,B1900108800000,Os Jovens Baumann,Ficção,Brasil,Brasileira,2019-09-19 00:00:00,Vitrine Filmes,Distribuição Nacional,1,12,36.0
61119,2019,semana 52,B1900487100000,Os Parças 2,Ficção,Brasil,Brasileira,2019-11-28 00:00:00,Paris,Distribuição Nacional,107,18259,292181.0
61120,2019,semana 52,E1900458900000,Papicha,Ficção,"Argélia, Bélgica, França, Qatar",Estrangeira,2019-10-31 00:00:00,Pandora Filmes,Distribuição Nacional,1,8,70.0
61121,2019,semana 52,E1900453900000,Parasita,Ficção,Coréia do Sul,Estrangeira,2019-11-07 00:00:00,Alpha Filmes,Distribuição Nacional,26,10429,198050.0
61122,2019,semana 52,E1900162100000,Pets: A Vida Secreta Dos Bichos 2,Ficção,"Estados Unidos, França, Japão",Estrangeira,2019-06-27 00:00:00,Universal,Distribuição Internacional,1,22,107.0
61123,2019,semana 52,E1900127400000,Playmobil - O Filme,Animação,"Alemanha, França",Estrangeira,2019-12-19 00:00:00,Paris,Distribuição Nacional,255,37417,593570.0
61124,2019,semana 52,E1900302600000,Rainha De Copas,Ficção,"Dinamarca, Suécia",Estrangeira,2019-09-12 00:00:00,Arteplex,Distribuição Nacional,1,66,790.0
61125,2019,semana 52,E1900499200000,Retablo,Ficção,"Alemanha, Noruega, Peru",Estrangeira,2019-11-07 00:00:00,Arteplex,Distribuição Nacional,2,28,548.0
61126,2019,semana 52,E1900358900000,Star Wars: A Ascensão Skywalker,Ficção,Estados Unidos,Estrangeira,2019-12-19 00:00:00,Disney,Distribuição Internacional,1669,681068,13105649.0
61127,2019,semana 52,E1900525400000,Synonyms,Ficção,"Alemanha, França, Israel",Estrangeira,2019-12-12 00:00:00,Fênix Filmes/Escarlate,Distribuição Nacional,12,1258,23111.0
61128,2019,semana 52,E1900229100000,Toy Story 4,Animação,Estados Unidos,Estrangeira,2019-06-20 00:00:00,Disney,Distribuição Internacional,1,49,479.0
61129,2019,semana 52,E1900431700000,Um Amante Francês,Ficção,França,Estrangeira,2019-11-28 00:00:00,Pagu Pictures,Distribuição Nacional,1,44,434.0
61130,2019,semana 52,E1900466900000,Um Dia De Chuva Em Nova York,Ficção,Estados Unidos,Estrangeira,2019-11-21 00:00:00,Imagem,Distribuição Nacional,12,2662,57290.0
61131,2019,semana 52,B1800552500000,Um Dia Para Susana,Documentário,Brasil,Brasileira,2019-10-03 00:00:00,Vitrine Filmes,Distribuição Nacional,1,12,36.0
61132,2019,semana 52,B1900177100000,Uma,Documentário,"Brasil, Índia",Brasileira,2019-11-21 00:00:00,Espaço Filmes,Distribuição Nacional,2,73,1345.0
61133,2019,semana 52,E1900436800000,Uma Segunda Chance Para Amar,Ficção,"Estados Unidos, Reino Unido",Estrangeira,2019-11-28 00:00:00,Universal,Distribuição Internacional,32,2572,41975.0

In [6]:
df.dtypes

Ano de exibição                          int64
Semana de exibição                      object
CPB/ROE                                 object
Título da obra                          object
Gênero                                  object
País(es) produtor(es) da obra           object
Nacionalidade da obra                   object
Data de Lançamento                      object
Distribuidora                           object
Origem da empresa distribuidora         object
Número de salas na semana dos dados      int64
Público na semana dos dados              int64
Renda (R$) na semana dos dados         float64
dtype: object

In [7]:
#Identificar o problema da coluna Data de Lançamento
df['Data de Lançamento'].value_counts()

Relançamento           649
2014-10-23 00:00:00    250
2012-12-21 00:00:00    233
2015-08-20 00:00:00    198
2009-06-05 00:00:00    198
                      ...
2014-12-13 00:00:00      1
1978-12-14 00:00:00      1
2006-10-13 00:00:00      1
2005-05-13 00:00:00      1
2014-03-28 00:00:00      1
Name: Data de Lançamento, Length: 879, dtype: int64

In [8]:
# Exibir alguns filmes com data = Relançamento
df[df['Data de Lançamento'] == 'Relançamento'].head()

,Ano de exibição,Semana de exibição,CPB/ROE,Título da obra,Gênero,País(es) produtor(es) da obra,Nacionalidade da obra,Data de Lançamento,Distribuidora,Origem da empresa distribuidora,Número de salas na semana dos dados,Público na semana dos dados,Renda (R$) na semana dos dados
519,2009,semana 05,E1600589800000,Os Contos de Canterbury,Ficção,Itália,Estrangeira,Relançamento,Pandora Filmes,Distribuição Nacional,1,886,6758.5
636,2009,semana 06,E1600589800000,Os Contos de Canterbury,Ficção,Itália,Estrangeira,Relançamento,Pandora Filmes,Distribuição Nacional,1,707,4378.0
746,2009,semana 07,E1600589800000,Os Contos de Canterbury,Ficção,Itália,Estrangeira,Relançamento,Pandora Filmes,Distribuição Nacional,1,432,2765.5
847,2009,semana 08,E1600589800000,Os Contos de Canterbury,Ficção,Itália,Estrangeira,Relançamento,Pandora Filmes,Distribuição Nacional,1,473,2990.5
956,2009,semana 09,E1600589800000,Os Contos de Canterbury,Ficção,Itália,Estrangeira,Relançamento,Pandora Filmes,Distribuição Nacional,1,281,1800.5

# Decisão sobre dados incorretos/ Faltantes/ Divergentes

In [9]:
df.shape

(61134, 13)

In [10]:
# Criar um novo DataFrame sem os Relançamentos
df_novo = df[df['Data de Lançamento'] != 'relançamento'].copy()

In [11]:
df_novo.head()

,Ano de exibição,Semana de exibição,CPB/ROE,Título da obra,Gênero,País(es) produtor(es) da obra,Nacionalidade da obra,Data de Lançamento,Distribuidora,Origem da empresa distribuidora,Número de salas na semana dos dados,Público na semana dos dados,Renda (R$) na semana dos dados
0,2009,semana 01,E1402431200000,007 Quantum of Solace,Ficção,"Estados Unidos, Inglaterra",Estrangeira,2008-11-07 00:00:00,Sony,Distribuição Internacional,31,4597,24719.0
1,2009,semana 01,B0700678800000,5 Frações de uma Quase História,Ficção,Brasil,Brasileira,2008-05-09 00:00:00,Usina Digital,Distribuição Nacional,1,24,120.5
2,2009,semana 01,E1600541500000,A Alegria de Emma,Ficção,Alemanha,Estrangeira,2008-10-03 00:00:00,Pandora Filmes,Distribuição Nacional,1,42,700.0
3,2009,semana 01,E1600594000000,A Bela Junie,Ficção,França,Estrangeira,2009-01-01 00:00:00,Imovision,Distribuição Nacional,2,1331,15710.5
4,2009,semana 01,E1600127600000,A Casa das Coelhinhas,Ficção,Estados Unidos,Estrangeira,2008-10-10 00:00:00,Sony,Distribuição Internacional,4,402,2011.0

In [12]:
df_novo['Data de Lançamento'].value_counts()

Relançamento           649
2014-10-23 00:00:00    250
2012-12-21 00:00:00    233
2015-08-20 00:00:00    198
2009-06-05 00:00:00    198
                      ...
2014-12-13 00:00:00      1
1978-12-14 00:00:00      1
2006-10-13 00:00:00      1
2005-05-13 00:00:00      1
2014-03-28 00:00:00      1
Name: Data de Lançamento, Length: 878, dtype: int64

In [13]:
df_novo1 = df_novo[df_novo['Data de Lançamento'] != 'relançamento'].copy()

In [14]:
df_novo1.dtypes

Ano de exibição                          int64
Semana de exibição                      object
CPB/ROE                                 object
Título da obra                          object
Gênero                                  object
País(es) produtor(es) da obra           object
Nacionalidade da obra                   object
Data de Lançamento                      object
Distribuidora                           object
Origem da empresa distribuidora         object
Número de salas na semana dos dados      int64
Público na semana dos dados              int64
Renda (R$) na semana dos dados         float64
dtype: object

In [15]:
df_novo1['Data de Lançamento'] = pd.to_datetime(df_novo1['Data de Lançamento'])

ParserError: Unknown string format: Relançamento

In [ ]:
df_novo1.dtypes

In [ ]:
df_novo1['Data de Lançamento'].shape

In [ ]:
# Quais os anos tivemos mais filmes lançados
df_novo1['Data de Lançamento'].dt.year.value_counts()

In [ ]:
# Plotar um gráfico com os filmes exibidos por ano
df_novo1['Data de Lançamento'].dt.year.value_counts().plot.bar(title = 'Exibição por Ano')

In [ ]:
# Qual o filme que teve maior bilheteria
df_novo1[df_novo1['Renda (R$) na semana dos dados'] == df_novo1['Renda (R$) na semana dos dados'].max()]

In [ ]:
#Os três filmes com maior bilheteria
df_novo1.nlargest(3, 'Renda (R$) na semana dos dados')

In [ ]:
# Qual o filme com menor bilheteria
df_novo1[df_novo1['Renda (R$) na semana dos dados'] == df_novo1['Renda (R$) na semana dos dados'].min()]

In [ ]:
# Quantos filmes são brasileiros e estrangeiros
df_novo1['Nacionalidade da obra'].value_counts()